server:
  port: 8081

spring:
  # 여기에 이름을 넣어줘야 함
  application:
    name: store-admin
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # validate : Entity와 DB의 스키마를 비교하여 차이가 있으면 오류를 발생시킨다.
      ddl-auto: validate

  datasource:
    # jdbc:mysql://localhost:3306/[TABLE NAME]?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://121.254.195.229:3306/delivery?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "df159357"

token:
  secret:
    key: "SpringBootJWTHelperTokenSecretKeyValue123!@#"
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12